### ISSUE TITLE
Adding juice to the forecasts

### ISSUE THREAD

**Issue by naevtamarkus** [izacus/hass-swissweather#12]
Thanks a lot for the integration! I started downloading some stuff from the API and ended up spending too much time on very simple stuff, and your code works like a charm.

I'd like to ask if it's possible to add a bit mote information regarding expected precipitation. In the forecast I can see temperatures and the icon for rain/sun, but not how many mm of water should one expect. Where I live it rains frequently, and 2 or 20 mm makes a big difference. Hourly and daily would be awesome, like in the official app, where they provide ranges. This way one can see, at a glance, if you must take the umbrella with you. One example: if you add the weather card in your dashboard and ask for secondary attributes, the precipitation is not there. Many other values are there already, like wind. Could it be a missing property in weather.py? I can see the precipitation in the sensors, though.

My second goal would be to use the forecast in automations. For instance: I'd like to water the garden if the forecasted precipitation for today is expected to be below 20mm. Get an alert if the wind is expected to be over 40 km/h today (not after it happened), things like this. I was looking at what one can do already from an automation, and it's possible to use the weather.weather_at_6900 attributes to see the current state (e.g. it rains now) but it's not possible to automate on the forecast. I was thinking a possibility could be to add a couple of entities with the forecast for today and the forecast for tomorrow, for instance, something like weather.forecast_today_at_6900 and weather.forecast_tomorrow_at_6900... what do you think?

I know how to code and could find the time to help... my problem is that I have 0 experience with home assistant stuff. Looking at your code, this seems to be 80% of this stuff, unfortunately. But with some guidance maybe I can contribute, please let me know.

Thanks again!!

**Comment by Benschi99** [comment]
https://www.home-assistant.io/integrations/weather/

Please have a look at this page. The forecast function will provide everything you are looking for regarding precipitation.

**Comment by Benschi99** [comment]
The default weather integration of Home Assistant can't produce any forecasts without any third party integrations feeding it data. And this Meteo Swiss integration is supporting it. Not sure how to explain it any easier, maybe worth to watch some tutorials about it.

**Comment by elmakus** [comment]
This does not need additional forecast entities in the integration. Current Home Assistant exposes the data through the response-returning `weather.get_forecasts` action, and Swiss Weather advertises both hourly and daily forecasts. For the specific “sum forecast rain for the next 24 hours” use case, an automation can do:

```yaml
- action: weather.get_forecasts
  target:
    entity_id: weather.weather_at_6900
  data:
    type: hourly
  response_variable: swiss_forecast

- condition: template
  value_template: >
    {% set ns = namespace(total_mm=0) %}
    {% for hour in swiss_forecast["weather.weather_at_6900"].forecast[:24] %}
      {% set ns.total_mm = ns.total_mm + (hour.precipitation | float(0)) %}
    {% endfor %}
    {{ ns.total_mm < 6 }}
```

The following actions run only when the predicted total for those 24 hourly intervals is below 6 mm. For a calendar-day value, call the same action with `type: daily` and inspect the selected entry precipitation instead. The action response also contains `precipitation_probability` where the provider supplies it.

Current HA documentation: https://www.home-assistant.io/actions/weather.get_forecasts/

So the automation part of this issue is already supported; a README example might still be worthwhile, but separate `forecast_today` / `forecast_tomorrow` entities would duplicate the native weather API.
